### ISSUE TITLE
Parse error on some URLs

### ISSUE THREAD

**Issue by danvonk** [chmike/CxxUrl#1]
The library seems to work well for the most part, except i'm unable to parse my website url (which is definitely valid) or any other url with 'nv' next to each other.

For the record, i'm using GCC 5.2.0.

``` c++
#include <iostream>
#include "url.hpp"

using namespace std;

int main() {
    Url url("https://danvonk.com");
    cout << url.str() << endl;
    return 0;
}
```

```
terminate called after throwing an instance of 'Url::parse_error'
  what():  IP address 'dan' in 'https://danvonk.com' is unsupported

Process finished with exit code 134
```

Any help on the issue would be much appreciated.
Thanks

**Comment by chmike** [comment]
Hello Danvonk. I confirm the bug.

**Comment by chmike** [comment]
The bug has been fixed.
