### ISSUE TITLE
Not encoding colon in query key/value

### ISSUE THREAD

**Issue by ivosu** [chmike/CxxUrl#11]
When adding query key/value containing colon, it stays unencoded.

**Comment by chmike** [comment]
CxxUrl is an url parser. It is not intended to modify or extend urls. 
Is the problem you report related to parsing ?

**Comment by ivosu** [comment]
Oh I see...
this is very confusing, as in your README you don't mention this, you even mention "Setting the different fields of an Url object" with example adding a query and have public `add_query` method.
In that case, I suggest altering the README a little bit so this is clear.
Thanks anyway for letting me know 👍

**Comment by chmike** [comment]
I will check what I did. Maybe I’m wrong. This is old now, and I didn’t program in C++ for years now.

**Comment by chmike** [comment]
You are right. 

I have to fully review the code. What you report is then a significant shortcoming of the library.

**Comment by chmike** [comment]
According to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986), the query part of the URL is `query = *( pchar / "/" / "?" )` (page 24), and `pchar` is defined as `pchar = unreserved / pct-encoded / sub-delims / ":" / "@"` (page 23) which means that the colon (:) does not need to be percent encoded. 

Thus to me, the current code is correct.
