### ISSUE TITLE
Support for "origin" concept

### ISSUE THREAD

**Issue by domfarolino** [chmike/CxxUrl#4]
From #2 I can see you've already found WHATWG's URL standard, but I was going to ask if there were any plans to support an URL's [origin](https://url.spec.whatwg.org/#concept-url-origin) concept?

**Comment by chmike** [comment]
I won’t extend this code and its scope. 
Not sure I understand the origin concept.

**Comment by domfarolino** [comment]
An origin is basically a scheme + host + port + domain. On the web, the common security boundary is essentially an "origin", so it is useful to see if two URLs are same-origin or cross-origin etc. I figured it'd be useful for this URL library to support this concept, especially if you're going to support WHATWG URL parsing. For example, this library could be used by servers handling web requests etc, but if you won't extend this code, that answers that.
