### ISSUE TITLE
Improper encoding of accented characters

### ISSUE THREAD

**Issue by kubaspatny** [chmike/CxxUrl#5]
Hello,

I ran into isssues when encoding query values with accented chars.

Value: Radhošť.gpx
Correct encoded value: Radhos%CC%8Ct%CC%8C.gpx
Current encoded value: Radhos%/C%iCt%/C%iC.gpx

To fix, when encoding a char, the current implementation

`o<<'%'<<"0123456789ABCDEF"[c>>4]<<"0123456789ABCDEF"[c&0xF];`

was changed so that the char is first cast it to `uint8_t`:

`o<<'%'<<"0123456789ABCDEF"[((uint8_t)c)>>4]<<"0123456789ABCDEF"[((uint8_t)c)&0xF];`

**Comment by chmike** [comment]
Thank you for the bug report and fix suggestion. 
Code has been modified accordingly.
